
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R K PC
 */
public class AKLUJ_APMC extends javax.swing.JFrame {

    PreparedStatement p;
    ResultSet R;
    Connection con;
    
    public AKLUJ_APMC() {
        initComponents();
        
        
        String url = "jdbc:mysql://localhost:3306/farm in hand";
        String user ="root";
        String pass = "";
        try
        {
            con = DriverManager.getConnection(url,user,pass);
        }catch(Exception A)
        {
            
        }
        
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AKLUJTABLE = new javax.swing.JTable();
        AKLUJ = new javax.swing.JButton();
        AKLUJ1 = new javax.swing.JButton();
        PRINT = new javax.swing.JButton();
        MAINWALL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,90));

        AKLUJTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "RATE", "DAY", "MONTH", "YEAR"
            }
        ));
        jScrollPane1.setViewportView(AKLUJTABLE);

        AKLUJ.setBackground(new java.awt.Color(128, 128, 128));
        AKLUJ.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        AKLUJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/store-sign (1).png"))); // NOI18N
        AKLUJ.setText(" SHOW DATA");
        AKLUJ.setBorder(null);
        AKLUJ.setBorderPainted(false);
        AKLUJ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AKLUJ.setOpaque(false);
        AKLUJ.setSelected(true);
        AKLUJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AKLUJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AKLUJFocusLost(evt);
            }
        });
        AKLUJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AKLUJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AKLUJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AKLUJMouseExited(evt);
            }
        });
        AKLUJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AKLUJActionPerformed(evt);
            }
        });

        AKLUJ1.setBackground(new java.awt.Color(128, 128, 128));
        AKLUJ1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        AKLUJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/arrow-98-24.png"))); // NOI18N
        AKLUJ1.setBorder(null);
        AKLUJ1.setBorderPainted(false);
        AKLUJ1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AKLUJ1.setOpaque(false);
        AKLUJ1.setSelected(true);
        AKLUJ1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AKLUJ1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AKLUJ1FocusLost(evt);
            }
        });
        AKLUJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AKLUJ1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AKLUJ1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AKLUJ1MouseExited(evt);
            }
        });

        PRINT.setBackground(new java.awt.Color(128, 128, 128));
        PRINT.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        PRINT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/printer-24.png"))); // NOI18N
        PRINT.setText(" PRINT");
        PRINT.setBorder(null);
        PRINT.setBorderPainted(false);
        PRINT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PRINT.setOpaque(false);
        PRINT.setSelected(true);
        PRINT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PRINTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PRINTFocusLost(evt);
            }
        });
        PRINT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRINTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PRINTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PRINTMouseExited(evt);
            }
        });
        PRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AKLUJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AKLUJ, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRINT, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AKLUJ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PRINT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AKLUJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 540, 250));

        MAINWALL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/APMCM_AK.png"))); // NOI18N
        getContentPane().add(MAINWALL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        setSize(new java.awt.Dimension(600, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AKLUJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AKLUJFocusGained
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GRAY);
        AKLUJ.setBorder(panelm);
    }//GEN-LAST:event_AKLUJFocusGained

    private void AKLUJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AKLUJFocusLost
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        AKLUJ.setBorder(panelm);
    }//GEN-LAST:event_AKLUJFocusLost

    private void AKLUJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJMouseClicked
        
    }//GEN-LAST:event_AKLUJMouseClicked

    private void AKLUJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJMouseEntered
        Border panelm = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        AKLUJ.setBorder(panelm);
        AKLUJ.setBackground(Color.GREEN);
    }//GEN-LAST:event_AKLUJMouseEntered

    private void AKLUJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJMouseExited
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        AKLUJ.setBorder(panelm);
        AKLUJ.setBackground(Color.gray);
    }//GEN-LAST:event_AKLUJMouseExited

    private void AKLUJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AKLUJActionPerformed
       String sql = "SELECT * FROM `akluj_update`"; 
            try 
            {
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                DefaultTableModel TBmodel = (DefaultTableModel)AKLUJTABLE.getModel();
                TBmodel.setNumRows(0);
                        while (rs.next())
                        {
                            TBmodel.addRow(new String[]{rs.getString(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
                            
                        }
                            
            }catch(Exception e){}
    }//GEN-LAST:event_AKLUJActionPerformed

    private void AKLUJ1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AKLUJ1FocusGained
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GRAY);
        AKLUJ.setBorder(panelm);
    }//GEN-LAST:event_AKLUJ1FocusGained

    private void AKLUJ1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AKLUJ1FocusLost
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        AKLUJ.setBorder(panelm);
    }//GEN-LAST:event_AKLUJ1FocusLost

    private void AKLUJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJ1MouseClicked
        APMCS AK = new APMCS();
        AK.show(true);
        this.dispose();
    }//GEN-LAST:event_AKLUJ1MouseClicked

    private void AKLUJ1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJ1MouseEntered
        Border panelm = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        AKLUJ1.setBorder(panelm);
        AKLUJ1.setBackground(Color.GREEN);
    }//GEN-LAST:event_AKLUJ1MouseEntered

    private void AKLUJ1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJ1MouseExited
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        AKLUJ1.setBorder(panelm);
        AKLUJ1.setBackground(Color.gray);
    }//GEN-LAST:event_AKLUJ1MouseExited

    private void PRINTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PRINTFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTFocusGained

    private void PRINTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PRINTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTFocusLost

    private void PRINTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTMouseClicked

    private void PRINTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseEntered

        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        PRINT.setBorder(panelA);
        PRINT.setBackground(Color.GREEN);

    }//GEN-LAST:event_PRINTMouseEntered

    private void PRINTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseExited

        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY);
        PRINT.setBorder(panelA);
        PRINT.setBackground(Color.GRAY);

    }//GEN-LAST:event_PRINTMouseExited

    private void PRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINTActionPerformed
        try
        {
            AKLUJTABLE.print();
        }catch(Exception ec){}
    }//GEN-LAST:event_PRINTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AKLUJ_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AKLUJ_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AKLUJ_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AKLUJ_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AKLUJ_APMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AKLUJ;
    private javax.swing.JButton AKLUJ1;
    private javax.swing.JTable AKLUJTABLE;
    private javax.swing.JLabel MAINWALL1;
    private javax.swing.JButton PRINT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
