
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R K PC
 */
public class APMCS extends javax.swing.JFrame {

    /**
     * Creates new form FORCLASDEMO
     */
    public APMCS() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Border panelINDA = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        INDAPUR.setBorder(panelINDA);
        
        Border panelBMT = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        BARAMATI.setBorder(panelBMT);
        
        Border panelIND = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        AKLUJ.setBorder(panelIND);
        
        Border paneCL = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_CLOSE.setBorder(paneCL);
        BACK.setBorder(paneCL);
        
        Border L = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        APMCADMIN1.setBorder(L);
        
        Border panelmi = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_MINI.setBorder(panelmi);
        //INDAPURAPMC.setBackground(Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        INDAPUR = new javax.swing.JButton();
        BARAMATI = new javax.swing.JButton();
        AKLUJ = new javax.swing.JButton();
        APMCADMIN = new javax.swing.JButton();
        APMCADMIN1 = new javax.swing.JButton();
        jLabel_CLOSE = new javax.swing.JLabel();
        jLabel_MINI = new javax.swing.JLabel();
        BACK = new javax.swing.JLabel();
        MAIN_WALL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 90));

        INDAPUR.setBackground(new java.awt.Color(128, 128, 128));
        INDAPUR.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        INDAPUR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/store-sign (1).png"))); // NOI18N
        INDAPUR.setText(" INDAPUR APMC");
        INDAPUR.setBorder(null);
        INDAPUR.setBorderPainted(false);
        INDAPUR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INDAPUR.setOpaque(false);
        INDAPUR.setSelected(true);
        INDAPUR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                INDAPURFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                INDAPURFocusLost(evt);
            }
        });
        INDAPUR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INDAPURMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                INDAPURMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                INDAPURMouseExited(evt);
            }
        });

        BARAMATI.setBackground(new java.awt.Color(128, 128, 128));
        BARAMATI.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        BARAMATI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/store-sign (1).png"))); // NOI18N
        BARAMATI.setText(" BARAMATI APMC");
        BARAMATI.setBorder(null);
        BARAMATI.setBorderPainted(false);
        BARAMATI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BARAMATI.setOpaque(false);
        BARAMATI.setSelected(true);
        BARAMATI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BARAMATIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BARAMATIFocusLost(evt);
            }
        });
        BARAMATI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BARAMATIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BARAMATIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BARAMATIMouseExited(evt);
            }
        });

        AKLUJ.setBackground(new java.awt.Color(128, 128, 128));
        AKLUJ.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        AKLUJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/store-sign (1).png"))); // NOI18N
        AKLUJ.setText(" AKLUJ APMC");
        AKLUJ.setBorder(null);
        AKLUJ.setBorderPainted(false);
        AKLUJ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AKLUJ.setOpaque(false);
        AKLUJ.setSelected(true);
        AKLUJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AKLUJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AKLUJFocusLost(evt);
            }
        });
        AKLUJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AKLUJMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AKLUJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AKLUJMouseExited(evt);
            }
        });

        APMCADMIN.setBackground(new java.awt.Color(128, 128, 128));
        APMCADMIN.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        APMCADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/administrator-24.png"))); // NOI18N
        APMCADMIN.setText(" ADMIN'S");
        APMCADMIN.setBorder(null);
        APMCADMIN.setBorderPainted(false);
        APMCADMIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        APMCADMIN.setOpaque(false);
        APMCADMIN.setSelected(true);
        APMCADMIN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                APMCADMINFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                APMCADMINFocusLost(evt);
            }
        });
        APMCADMIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APMCADMINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                APMCADMINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                APMCADMINMouseExited(evt);
            }
        });
        APMCADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APMCADMINActionPerformed(evt);
            }
        });

        APMCADMIN1.setBackground(new java.awt.Color(128, 128, 128));
        APMCADMIN1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        APMCADMIN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/triple-tap-2-24.png"))); // NOI18N
        APMCADMIN1.setText(" APPLY ");
        APMCADMIN1.setBorder(null);
        APMCADMIN1.setBorderPainted(false);
        APMCADMIN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        APMCADMIN1.setOpaque(false);
        APMCADMIN1.setSelected(true);
        APMCADMIN1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                APMCADMIN1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                APMCADMIN1FocusLost(evt);
            }
        });
        APMCADMIN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                APMCADMIN1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                APMCADMIN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                APMCADMIN1MouseExited(evt);
            }
        });
        APMCADMIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APMCADMIN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INDAPUR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BARAMATI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AKLUJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APMCADMIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APMCADMIN1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(INDAPUR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(BARAMATI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(AKLUJ, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(APMCADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(APMCADMIN1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 270));

        jLabel_CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/redclose.png"))); // NOI18N
        jLabel_CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CLOSEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_CLOSEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CLOSEMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 27, 27));

        jLabel_MINI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/MINIM.png"))); // NOI18N
        jLabel_MINI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MINI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MINIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MINIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MINIMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_MINI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 27, 27));

        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/arrow-98-24.png"))); // NOI18N
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKMouseExited(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        MAIN_WALL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/APMC_PIC.jpg"))); // NOI18N
        getContentPane().add(MAIN_WALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        setSize(new java.awt.Dimension(400, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void INDAPURFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_INDAPURFocusGained
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GRAY);
        INDAPUR.setBorder(panelm);
        //jButton_FARM.setBackground(Color.GRAY);
    }//GEN-LAST:event_INDAPURFocusGained

    private void INDAPURFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_INDAPURFocusLost
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        INDAPUR.setBorder(panelm);
        //jButton_FARM.setBackground(Color.GREEN);
    }//GEN-LAST:event_INDAPURFocusLost

    private void INDAPURMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INDAPURMouseClicked
        INDAPUR_APMC IAP = new INDAPUR_APMC();
        IAP.show();
        this.dispose();
    }//GEN-LAST:event_INDAPURMouseClicked

    private void INDAPURMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INDAPURMouseEntered
        Border panelm = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        INDAPUR.setBorder(panelm);
        INDAPUR.setBackground(Color.GREEN);
    }//GEN-LAST:event_INDAPURMouseEntered

    private void INDAPURMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INDAPURMouseExited

        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        INDAPUR.setBorder(panelm);
        INDAPUR.setBackground(Color.gray);
    }//GEN-LAST:event_INDAPURMouseExited

    private void BARAMATIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BARAMATIFocusGained
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GRAY);
        BARAMATI.setBorder(panelm);
    }//GEN-LAST:event_BARAMATIFocusGained

    private void BARAMATIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BARAMATIFocusLost
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        BARAMATI.setBorder(panelm);
    }//GEN-LAST:event_BARAMATIFocusLost

    private void BARAMATIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BARAMATIMouseClicked
        BMT_APMC BMP = new BMT_APMC();
        BMP.show();
        this.dispose();
    }//GEN-LAST:event_BARAMATIMouseClicked

    private void BARAMATIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BARAMATIMouseEntered
        Border panelm = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        BARAMATI.setBorder(panelm);
        BARAMATI.setBackground(Color.GREEN);

    }//GEN-LAST:event_BARAMATIMouseEntered

    private void BARAMATIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BARAMATIMouseExited
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        BARAMATI.setBorder(panelm);
        BARAMATI.setBackground(Color.gray);
    }//GEN-LAST:event_BARAMATIMouseExited

    private void AKLUJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AKLUJFocusGained
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GRAY);
        AKLUJ.setBorder(panelm);
    }//GEN-LAST:event_AKLUJFocusGained

    private void AKLUJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AKLUJFocusLost
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        AKLUJ.setBorder(panelm);
    }//GEN-LAST:event_AKLUJFocusLost

    private void AKLUJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJMouseClicked
        AKLUJ_APMC AK = new AKLUJ_APMC();
        AK.show(true);
        this.dispose();
    }//GEN-LAST:event_AKLUJMouseClicked

    private void AKLUJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJMouseEntered
        Border panelm = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        AKLUJ.setBorder(panelm);
        AKLUJ.setBackground(Color.GREEN);

    }//GEN-LAST:event_AKLUJMouseEntered

    private void AKLUJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AKLUJMouseExited
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        AKLUJ.setBorder(panelm);
        AKLUJ.setBackground(Color.gray);
    }//GEN-LAST:event_AKLUJMouseExited

    private void jLabel_CLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CLOSEMouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel_CLOSEMouseClicked

    private void jLabel_CLOSEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CLOSEMouseEntered
        Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.red);
        jLabel_CLOSE.setBorder(panelCE);
    }//GEN-LAST:event_jLabel_CLOSEMouseEntered

    private void jLabel_CLOSEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CLOSEMouseExited
       Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_CLOSE.setBorder(panelCE);
    }//GEN-LAST:event_jLabel_CLOSEMouseExited

    private void jLabel_MINIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MINIMouseEntered
        Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.GRAY);
        jLabel_MINI.setBorder(panelCE);
    }//GEN-LAST:event_jLabel_MINIMouseEntered

    private void jLabel_MINIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MINIMouseExited
       Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_MINI.setBorder(panelCE);
    }//GEN-LAST:event_jLabel_MINIMouseExited

    private void APMCADMINFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APMCADMINFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_APMCADMINFocusGained

    private void APMCADMINFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APMCADMINFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_APMCADMINFocusLost

    private void APMCADMINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCADMINMouseClicked
       APMCADMINS_LOGIN lg = new APMCADMINS_LOGIN();
       lg.show();
       this.dispose();
    }//GEN-LAST:event_APMCADMINMouseClicked

    private void APMCADMINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCADMINMouseEntered
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        APMCADMIN.setBorder(panelA);
        APMCADMIN.setBackground(Color.GREEN);

    }//GEN-LAST:event_APMCADMINMouseEntered

    private void APMCADMINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCADMINMouseExited
        Border panelm = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.gray);
        APMCADMIN.setBorder(panelm);
        APMCADMIN.setBackground(Color.gray);
    }//GEN-LAST:event_APMCADMINMouseExited

    private void APMCADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APMCADMINActionPerformed
       // APMCADMINS_LOGIN APAD = new APMCADMINS_LOGIN();
        //APAD.show();
    }//GEN-LAST:event_APMCADMINActionPerformed

    private void APMCADMIN1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APMCADMIN1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_APMCADMIN1FocusGained

    private void APMCADMIN1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_APMCADMIN1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_APMCADMIN1FocusLost

    private void APMCADMIN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCADMIN1MouseClicked
        APPLYER_PAGE HP = new APPLYER_PAGE();
        HP.show();
        this.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_APMCADMIN1MouseClicked

    private void APMCADMIN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCADMIN1MouseEntered
        Border panelA = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.GREEN);
        APMCADMIN1.setBorder(panelA);
        APMCADMIN1.setBackground(Color.GREEN);
    }//GEN-LAST:event_APMCADMIN1MouseEntered

    private void APMCADMIN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCADMIN1MouseExited
        Border panelm = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.gray);
        APMCADMIN1.setBorder(panelm);
        APMCADMIN1.setBackground(Color.gray);
    }//GEN-LAST:event_APMCADMIN1MouseExited

    private void APMCADMIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APMCADMIN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_APMCADMIN1ActionPerformed

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        HOMESCREEN HC = new HOMESCREEN();
        HC.show();
        this.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BACKMouseClicked

    private void BACKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseEntered
        Border panelA = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.GRAY);
        BACK.setBorder(panelA);
    }//GEN-LAST:event_BACKMouseEntered

    private void BACKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseExited
        Border panelA = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        BACK.setBorder(panelA);
    }//GEN-LAST:event_BACKMouseExited

    private void jLabel_MINIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MINIMouseClicked
        this.setExtendedState(APMCS.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel_MINIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APMCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APMCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APMCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APMCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APMCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AKLUJ;
    private javax.swing.JButton APMCADMIN;
    private javax.swing.JButton APMCADMIN1;
    private javax.swing.JLabel BACK;
    private javax.swing.JButton BARAMATI;
    private javax.swing.JButton INDAPUR;
    private javax.swing.JLabel MAIN_WALL;
    private javax.swing.JLabel jLabel_CLOSE;
    private javax.swing.JLabel jLabel_MINI;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
