
//import static INDAPUR_APMC.INDAPURTABLE;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R K PC
 */
public class APPLYER_PAGE extends javax.swing.JFrame {

   PreparedStatement p,ps;
   ResultSet R,rs;
   Connection con,cons;
    
    public APPLYER_PAGE() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
     Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        FIRSTNAME.setBorder(firs);
        LASTNAME.setBorder(firs);
        USERID.setBorder(firs);
        CREATEPASS.setBorder(firs);
        CONPASS.setBorder(firs);
        LICNO.setBorder(firs);
        ISSUAUT.setBorder(firs);
        MOBNO.setBorder(firs);
        PANNO.setBorder(firs);
        CLOS.setBorder(firs);
        MIN.setBorder(firs);
        APMCNAME.setBorder(firs);
        
//    Border fir = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
//        APMCNAME.setBorder(fir);

        String url = "jdbc:mysql://localhost:3306/farm in hand";
        String user ="root";
        String pass = "";
        try
            {
                cons = DriverManager.getConnection(url,user,pass);
                                
            }
        catch (Exception e)
        {}
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MIN = new javax.swing.JLabel();
        CLOS = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FIRSTNAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LASTNAME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        USERID = new javax.swing.JTextField();
        SAVEDB = new javax.swing.JButton();
        CREATEPASS = new javax.swing.JPasswordField();
        CONPASS = new javax.swing.JPasswordField();
        MOBNO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PANNO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LICNO = new javax.swing.JTextField();
        ISSUAUT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        DOWNLOAD = new javax.swing.JButton();
        APMCNAME = new javax.swing.JTextField();
        MAINWALL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CHECK = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/MINIM.png"))); // NOI18N
        MIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MINMouseExited(evt);
            }
        });
        getContentPane().add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 27, 27));

        CLOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/redclose.png"))); // NOI18N
        CLOS.setText("x");
        CLOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLOSMouseExited(evt);
            }
        });
        getContentPane().add(CLOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 27, 27));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,90));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel1.setText("FIRST NAME :");

        FIRSTNAME.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        FIRSTNAME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FIRSTNAMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FIRSTNAMEMouseExited(evt);
            }
        });
        FIRSTNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FIRSTNAMEKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel2.setText("LAST NAME :");

        LASTNAME.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        LASTNAME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LASTNAMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LASTNAMEMouseExited(evt);
            }
        });
        LASTNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LASTNAMEKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel3.setText("CONFORM PASS :");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel4.setText("CREATE PASS:");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel5.setText("USER ID :");

        USERID.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        USERID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                USERIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                USERIDMouseExited(evt);
            }
        });
        USERID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                USERIDKeyPressed(evt);
            }
        });

        SAVEDB.setBackground(new java.awt.Color(128, 128, 128));
        SAVEDB.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        SAVEDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/triple-tap-2-24.png"))); // NOI18N
        SAVEDB.setText(" APPLY");
        SAVEDB.setBorder(null);
        SAVEDB.setBorderPainted(false);
        SAVEDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAVEDB.setOpaque(false);
        SAVEDB.setSelected(true);
        SAVEDB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SAVEDBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SAVEDBFocusLost(evt);
            }
        });
        SAVEDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAVEDBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SAVEDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SAVEDBMouseExited(evt);
            }
        });
        SAVEDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEDBActionPerformed(evt);
            }
        });

        CREATEPASS.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        CREATEPASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CREATEPASSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CREATEPASSMouseExited(evt);
            }
        });

        CONPASS.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        CONPASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CONPASSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CONPASSMouseExited(evt);
            }
        });

        MOBNO.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        MOBNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MOBNOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MOBNOMouseExited(evt);
            }
        });
        MOBNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MOBNOKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel9.setText("MOBILE NO :");

        PANNO.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        PANNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANNOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANNOMouseExited(evt);
            }
        });
        PANNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PANNOKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel10.setText("AADHAR NO :");

        jLabel11.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel11.setText("APMC :");

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel7.setText("LICENCE NO :");

        LICNO.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        LICNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LICNOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LICNOMouseExited(evt);
            }
        });
        LICNO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LICNOKeyPressed(evt);
            }
        });

        ISSUAUT.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        ISSUAUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ISSUAUTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ISSUAUTMouseExited(evt);
            }
        });
        ISSUAUT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ISSUAUTKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        jLabel8.setText("ISSUED AUTHORITY :");

        BACK.setBackground(new java.awt.Color(128, 128, 128));
        BACK.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/arrow-98-24.png"))); // NOI18N
        BACK.setBorder(null);
        BACK.setBorderPainted(false);
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.setOpaque(false);
        BACK.setSelected(true);
        BACK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BACKFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BACKFocusLost(evt);
            }
        });
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKMouseExited(evt);
            }
        });
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        DOWNLOAD.setBackground(new java.awt.Color(128, 128, 128));
        DOWNLOAD.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        DOWNLOAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/downloading.png"))); // NOI18N
        DOWNLOAD.setText(" PRINT");
        DOWNLOAD.setBorder(null);
        DOWNLOAD.setBorderPainted(false);
        DOWNLOAD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DOWNLOAD.setOpaque(false);
        DOWNLOAD.setSelected(true);
        DOWNLOAD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOWNLOADFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOWNLOADFocusLost(evt);
            }
        });
        DOWNLOAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOWNLOADMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DOWNLOADMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DOWNLOADMouseExited(evt);
            }
        });
        DOWNLOAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOWNLOADActionPerformed(evt);
            }
        });

        APMCNAME.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        APMCNAME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                APMCNAMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                APMCNAMEMouseExited(evt);
            }
        });
        APMCNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                APMCNAMEKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LICNO, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(USERID, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PANNO, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CONPASS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 69, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MOBNO, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CREATEPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(APMCNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ISSUAUT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SAVEDB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DOWNLOAD, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FIRSTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(LASTNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(USERID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CREATEPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(CONPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(MOBNO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(APMCNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(PANNO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LICNO, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ISSUAUT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOWNLOAD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVEDB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 300));

        MAINWALL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/HOST.png"))); // NOI18N
        getContentPane().add(MAINWALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/NOTICE.png"))); // NOI18N

        CHECK.setBackground(new java.awt.Color(255, 255, 255));
        CHECK.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        CHECK.setText(" I Under & I agree With This");
        CHECK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CHECK)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addComponent(CHECK))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 250, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FIRSTNAMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FIRSTNAMEMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        FIRSTNAME.setBorder(firs);
        FIRSTNAME.setBackground(Color.white);
    }//GEN-LAST:event_FIRSTNAMEMouseEntered

    private void FIRSTNAMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FIRSTNAMEMouseExited
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        FIRSTNAME.setBorder(firs);
        FIRSTNAME.setBackground(Color.white);
    }//GEN-LAST:event_FIRSTNAMEMouseExited

    private void LASTNAMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LASTNAMEMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        LASTNAME.setBorder(firs);
        LASTNAME.setBackground(Color.white);
    }//GEN-LAST:event_LASTNAMEMouseEntered

    private void LASTNAMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LASTNAMEMouseExited
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        LASTNAME.setBorder(firs);
        LASTNAME.setBackground(Color.white);
    }//GEN-LAST:event_LASTNAMEMouseExited

    private void USERIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERIDMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        USERID.setBorder(firs);
        USERID.setBackground(Color.white);
    }//GEN-LAST:event_USERIDMouseEntered

    private void USERIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USERIDMouseExited
       Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        USERID.setBorder(firs);
        USERID.setBackground(Color.white);
    }//GEN-LAST:event_USERIDMouseExited

    private void LICNOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LICNOMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        LICNO.setBorder(firs);
        LICNO.setBackground(Color.white);
    }//GEN-LAST:event_LICNOMouseEntered

    private void LICNOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LICNOMouseExited
       Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        LICNO.setBorder(firs);
        LICNO.setBackground(Color.white);
    }//GEN-LAST:event_LICNOMouseExited

    private void ISSUAUTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ISSUAUTMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        ISSUAUT.setBorder(firs);
        ISSUAUT.setBackground(Color.white);
    }//GEN-LAST:event_ISSUAUTMouseEntered

    private void ISSUAUTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ISSUAUTMouseExited
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        ISSUAUT.setBorder(firs);
        ISSUAUT.setBackground(Color.white);
    }//GEN-LAST:event_ISSUAUTMouseExited

    private void MOBNOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOBNOMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        MOBNO.setBorder(firs);
        MOBNO.setBackground(Color.white);
    }//GEN-LAST:event_MOBNOMouseEntered

    private void MOBNOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOBNOMouseExited
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        MOBNO.setBorder(firs);
        MOBNO.setBackground(Color.white);
    }//GEN-LAST:event_MOBNOMouseExited

    private void PANNOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANNOMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        PANNO.setBorder(firs);
        PANNO.setBackground(Color.white);
    }//GEN-LAST:event_PANNOMouseEntered

    private void PANNOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANNOMouseExited
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        PANNO.setBorder(firs);
        PANNO.setBackground(Color.white);
    }//GEN-LAST:event_PANNOMouseExited

    private void SAVEDBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SAVEDBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEDBFocusGained

    private void SAVEDBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SAVEDBFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_SAVEDBFocusLost

    private void SAVEDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEDBMouseClicked
        APPLYER_PAGE HP = new APPLYER_PAGE();
        HP.show();
        this.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SAVEDBMouseClicked

    private void SAVEDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEDBMouseEntered
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        SAVEDB.setBorder(panelA);
        SAVEDB.setBackground(Color.GREEN);
    }//GEN-LAST:event_SAVEDBMouseEntered

    private void SAVEDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAVEDBMouseExited
        Border panelm = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
        SAVEDB.setBorder(panelm);
        SAVEDB.setBackground(Color.gray);
    }//GEN-LAST:event_SAVEDBMouseExited

    public boolean verif()
    {
        
        if(FIRSTNAME.getText().equals("") || LASTNAME.getText().equals("") || USERID.getText().equals("") || CREATEPASS.getText().equals("") || CONPASS.getText().equals("") || LICNO.getText().equals("") || PANNO.getText().equals("") || APMCNAME.getText().equals("") || ISSUAUT.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "REMAINING FIELDS ARE REUIRED TO FILL");
            return false;
        }
               else if (FIRSTNAME.getText().equals(""))
                    {
                         JOptionPane.showMessageDialog(this,"USER NAME IS REQUIRED");
                         return false;
                    }
                  else if (LASTNAME.getText().equals(""))
                    {
                         JOptionPane.showMessageDialog(this,"LAST NAME IS REQUIRED");
                         return false;
                    }
                  else if(USERID.getText().equals(""))
                    {
                        JOptionPane.showMessageDialog(this,"USER ID IS REQUIRED");
                        return false;
                    }
                 else if (CREATEPASS.getText().equals(""))
                     {
                          JOptionPane.showMessageDialog(this,"FILL YOUR PASSWORD");
                          return false;
                      }
                 else if (CONPASS.getText().equals(""))
                     {
                          JOptionPane.showMessageDialog(this,"CONFORM YOUR PASSWORD");
                          return false;
                      }
                    else if(!CREATEPASS.getText().equals(CONPASS.getText()))
                        {
                           JOptionPane.showMessageDialog(this,"PASSWORD IS NOT MATCH");
                           return false;
                         } 
                   else if (MOBNO.getText().equals(""))
                    {
                         JOptionPane.showMessageDialog(this,"PLEAES ENTER YOUR MOBILE NUMBER");
                         return false;
                    }
                   else if (PANNO.getText().equals(""))
                    {
                         JOptionPane.showMessageDialog(this,"ENTER YOUR ADDHAR CARD NUMBER");
                         return false;
                    }
                    else if (APMCNAME.getText().equals(""))
                    {
                         JOptionPane.showMessageDialog(this,"PLEASE ENTER YOUR APMC NAME");
                         return false;
                    }
                    else if (LICNO.getText().equals(""))
                    {
                         JOptionPane.showMessageDialog(this,"PLEAES ENTER YOUR LICENSE NUMBER");
                         return false;
                    }
                    else if (ISSUAUT.getText().equals(""))
                    {
                         JOptionPane.showMessageDialog(this,"PLEASE ENTER, WHO ISSUE YOUR LICENSE");
                         return false;
                    }
                    if(!CHECK.isSelected())
                    {
                        JOptionPane.showMessageDialog(this,"PLEASE READ AND ACCEPT TERMS & CONDITION IF YOU AGREE!!");
                        return false;
                    } 
                    else 
                    {
                         return true;
                    }
       // return false;
    }

    
    
    private void SAVEDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEDBActionPerformed
        if(verif()){
   //EXECUTE DATA INTO THE DATABASE
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/farm in hand","root","");
            String sql = "INSERT INTO `host_page`(`FIRST NAME`, `LAST NAME`, `USER ID`, `PASSWORD`, `CON PASSWORD`, `LICENCE NO`, `ISSUED AUTHORITY`, `MOBILE NO`, `PAN NO`, `APMC NAME`) VALUES (?,?,?,?,?,?,?,?,?,?)";
            p = con.prepareStatement(sql);
            
            p.setString(1, FIRSTNAME.getText());
            p.setString(2, LASTNAME.getText());
            p.setString(3, USERID.getText());
            p.setString(4, CREATEPASS.getText());
            p.setString(5, CONPASS.getText());
            p.setString(6, LICNO.getText());
            p.setString(7, ISSUAUT.getText());
            p.setString(8, MOBNO.getText());
            p.setString(9, PANNO.getText());
            
            //String value = APMCUSER.getSelectedItem().toString();
            p.setString(10,APMCNAME.getText());
           
            p.executeUpdate();
            JOptionPane.showMessageDialog(this,FIRSTNAME.getText() +" "+ LASTNAME.getText() + " IS SUCESSFULLY RAGISTERED!!!");
            
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"INVALID");
        }        
    }//GEN-LAST:event_SAVEDBActionPerformed
    }
        
    private void CREATEPASSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEPASSMouseEntered
        Border panelA = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLUE);
        CREATEPASS.setBorder(panelA);
        CREATEPASS.setBackground(Color.WHITE);
    }//GEN-LAST:event_CREATEPASSMouseEntered

    private void CREATEPASSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEPASSMouseExited
        Border panelm = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        CREATEPASS.setBorder(panelm);
        CREATEPASS.setBackground(Color.WHITE);
    }//GEN-LAST:event_CREATEPASSMouseExited

    private void CONPASSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONPASSMouseEntered
        Border panelA = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLUE);
        CONPASS.setBorder(panelA);
        CONPASS.setBackground(Color.WHITE);
    }//GEN-LAST:event_CONPASSMouseEntered

    private void CONPASSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CONPASSMouseExited
         Border panelm = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        CONPASS.setBorder(panelm);
        CONPASS.setBackground(Color.WHITE);
    }//GEN-LAST:event_CONPASSMouseExited

    private void FIRSTNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIRSTNAMEKeyPressed
        
// THIS CODE IS FOR ONLY CHARACTERS VALUE WILL BE ADDED ONLY
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c))
        {
            FIRSTNAME.setEditable(true);
        }else
        {
            //JOptionPane.showMessageDialog(this,"YOU CAN'T USE ANY DIGIT OR SPECIAL SYMBOL\n IT WILL BE CLOSE YOUR CURRENT WINDOW","",JOptionPane.ERROR_MESSAGE);
            //dispose();
            FIRSTNAME.setEditable(false);
        }
    }//GEN-LAST:event_FIRSTNAMEKeyPressed

    private void LASTNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LASTNAMEKeyPressed
        // THIS CODE IS FOR ONLY CHARACTERS VALUE WILL BE ADDED ONLY
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c))
        {
            LASTNAME.setEditable(true);
        }else
        {
            //JOptionPane.showMessageDialog(this,"YOU CAN'T USE ANY DIGIT OR SPECIAL SYMBOL\n IT WILL BE CLOSE YOUR CURRENT WINDOW","",JOptionPane.ERROR_MESSAGE);
            //dispose();
            LASTNAME.setEditable(false);
        }
    }//GEN-LAST:event_LASTNAMEKeyPressed

    private void USERIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERIDKeyPressed
        // THIS CODE IS FOR ONLY CHARACTERS VALUE WILL BE ADDED ONLY
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c))
        {
            USERID.setEditable(true);
        }else
        {
            //JOptionPane.showMessageDialog(this,"YOU CAN'T USE ANY DIGIT OR SPECIAL SYMBOL\n IT WILL BE CLOSE YOUR CURRENT WINDOW","",JOptionPane.ERROR_MESSAGE);
            //dispose();
            USERID.setEditable(false);
        }
    }//GEN-LAST:event_USERIDKeyPressed

    private void ISSUAUTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ISSUAUTKeyPressed
        // THIS CODE IS FOR ONLY CHARACTERS VALUE WILL BE ADDED ONLY
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c))
        {
            ISSUAUT.setEditable(true);
        }else
        {
            //JOptionPane.showMessageDialog(this,"YOU CAN'T USE ANY DIGIT OR SPECIAL SYMBOL\n IT WILL BE CLOSE YOUR CURRENT WINDOW","",JOptionPane.ERROR_MESSAGE);
            //dispose();
            ISSUAUT.setEditable(false);
        }
    }//GEN-LAST:event_ISSUAUTKeyPressed

    private void MOBNOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MOBNOKeyPressed
       String phoneno =  MOBNO.getText();
       int length = phoneno.length();
       char c = evt.getKeyChar();
       if (evt.getKeyChar() >= '0' && evt.getKeyChar()<='9')
       {
           if (length<10)
           {
               MOBNO.setEditable(true);
           }else
           {
               MOBNO.setEditable(false);
           }
       }else
       {
           if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE)
           {
               MOBNO.setEditable(true);
           }else
           {
               MOBNO.setEditable(false);
           }
       }
    }//GEN-LAST:event_MOBNOKeyPressed

    private void LICNOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LICNOKeyPressed
       String phoneno =  LICNO.getText();
       int length = phoneno.length();
       char c = evt.getKeyChar();
       if (evt.getKeyChar() >= '0' && evt.getKeyChar()<='9')
       {
           if (length<6)
           {
               LICNO.setEditable(true);
           }else
           {
               LICNO.setEditable(false);
           }
       }else
       {
           if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE)
           {
               LICNO.setEditable(true);
           }else
           {
               LICNO.setEditable(false);
           }
       }
    }//GEN-LAST:event_LICNOKeyPressed

    private void BACKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BACKFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKFocusGained

    private void BACKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BACKFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKFocusLost

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        APMCS AP = new APMCS();
        AP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACKMouseClicked

    private void BACKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseEntered
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        BACK.setBorder(panelA);
        BACK.setBackground(Color.GREEN);
    }//GEN-LAST:event_BACKMouseEntered

    private void BACKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseExited
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY);
        BACK.setBorder(panelA);
        BACK.setBackground(Color.GRAY);
    }//GEN-LAST:event_BACKMouseExited

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    private void DOWNLOADFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOWNLOADFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWNLOADFocusGained

    private void DOWNLOADFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOWNLOADFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWNLOADFocusLost

    private void DOWNLOADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOWNLOADMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWNLOADMouseClicked

    private void DOWNLOADMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOWNLOADMouseEntered

        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        DOWNLOAD.setBorder(panelA);
        DOWNLOAD.setBackground(Color.GREEN);
    }//GEN-LAST:event_DOWNLOADMouseEntered

    private void DOWNLOADMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOWNLOADMouseExited

        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY);
        DOWNLOAD.setBorder(panelA);
        DOWNLOAD.setBackground(Color.GRAY);
    }//GEN-LAST:event_DOWNLOADMouseExited

    private void DOWNLOADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWNLOADActionPerformed
       /*String value = APMCUSER.getSelectedItem().toString();*/
      if(verif())
      {
       String fname,conp,lname,mob,pan,lic,user,apmcn,issu,RECIVE_TEXT;
        fname = FIRSTNAME.getText();
        lname = LASTNAME.getText();
        user = USERID.getText();
        conp = CONPASS.getText();
        mob = MOBNO.getText();
        pan = PANNO.getText();
        apmcn = APMCNAME.getText();
        lic = LICNO.getText();
       issu = ISSUAUT.getText();

       PRINT PRI = new PRINT();
       PRINT.RECIVE_TEXT.setText("--------------------------------------------------------\n\n Applicant Name :"+fname+lname+"\n\n User ID :"+user+"\n\n Password :"+conp+"\n\n Mobile Number :"+mob+"\n\n Pan Card No :"+pan+"\n\n APMC Name :"+apmcn+"\n\n Licence Number :"+lic+"\n\n Issued Authority :"+issu+"\n\n--------------------------------------------------------"+"\n\n Date :__:__:____ "+"\n\n Place :____________"+"\n\t\tSIGNATURE"+"\n\t\t"+"("+fname+" "+lname+")"+"\n\n\n Attatch's(Xerox Copy) \n 1). Adhaar Card \n 2). Licence \n 3). Declaretion \n 4). APMC NOC(for this APMC which You Mentioned)");
       
       PRI.setVisible(true);       
    }//GEN-LAST:event_DOWNLOADActionPerformed
    }
    private void CLOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSMouseClicked
        this.dispose();
    }//GEN-LAST:event_CLOSMouseClicked

    private void CLOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSMouseEntered
        Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.red);
        CLOS.setBorder(panelCE);
    }//GEN-LAST:event_CLOSMouseEntered

    private void CLOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSMouseExited
        Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        CLOS.setBorder(panelCE);
    }//GEN-LAST:event_CLOSMouseExited

    private void MINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINMouseClicked
        this.setExtendedState(BMT_UPDATE.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_MINMouseClicked

    private void MINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINMouseEntered
        Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.GRAY);
        MIN.setBorder(panelCE);
    }//GEN-LAST:event_MINMouseEntered

    private void MINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINMouseExited
        Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        MIN.setBorder(panelCE);
    }//GEN-LAST:event_MINMouseExited

    private void APMCNAMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCNAMEMouseEntered
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        APMCNAME.setBorder(firs);
        APMCNAME.setBackground(Color.white);
    }//GEN-LAST:event_APMCNAMEMouseEntered

    private void APMCNAMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APMCNAMEMouseExited
        Border firs = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        APMCNAME.setBorder(firs);
        APMCNAME.setBackground(Color.white);
    }//GEN-LAST:event_APMCNAMEMouseExited

    private void APMCNAMEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_APMCNAMEKeyPressed
        char c = evt.getKeyChar();
        
        if (Character.isLetter(c) || Character.isWhitespace(c)|| Character.isISOControl(c))
        {
            APMCNAME.setEditable(true);
        }else
        {
            //JOptionPane.showMessageDialog(this,"YOU CAN'T USE ANY DIGIT OR SPECIAL SYMBOL\n IT WILL BE CLOSE YOUR CURRENT WINDOW","",JOptionPane.ERROR_MESSAGE);
            //dispose();
            APMCNAME.setEditable(false);
        }
    }//GEN-LAST:event_APMCNAMEKeyPressed

    private void PANNOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PANNOKeyPressed
        String phoneno =  PANNO.getText();
       int length = phoneno.length();
       char c = evt.getKeyChar();
       if (evt.getKeyChar() >= '0' && evt.getKeyChar()<='9')
       {
           if (length<=11)
           {
               PANNO.setEditable(true);
           }else
           {
               PANNO.setEditable(false);
           }
       }else
       {
           if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE)
           {
               PANNO.setEditable(true);
           }else
           {
               PANNO.setEditable(false);
           }
       }
    }//GEN-LAST:event_PANNOKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APPLYER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APPLYER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APPLYER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APPLYER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APPLYER_PAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField APMCNAME;
    private javax.swing.JButton BACK;
    private javax.swing.JCheckBox CHECK;
    private javax.swing.JLabel CLOS;
    public static javax.swing.JPasswordField CONPASS;
    public static javax.swing.JPasswordField CREATEPASS;
    private javax.swing.JButton DOWNLOAD;
    public static javax.swing.JTextField FIRSTNAME;
    public static javax.swing.JTextField ISSUAUT;
    public static javax.swing.JTextField LASTNAME;
    public static javax.swing.JTextField LICNO;
    private javax.swing.JLabel MAINWALL;
    private javax.swing.JLabel MIN;
    public static javax.swing.JTextField MOBNO;
    public static javax.swing.JTextField PANNO;
    private javax.swing.JButton SAVEDB;
    public static javax.swing.JTextField USERID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
