
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static javafx.scene.control.ButtonType.CLOSE;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author R K PC
 */
public class INDAPUR_APMC extends javax.swing.JFrame {

    PreparedStatement p;
    ResultSet R;
    Connection con;
    
    public INDAPUR_APMC() {
        initComponents();
        
    Border pE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
    CLOSE.setBorder(pE);
    
    Border pWE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
    MINI.setBorder(pWE);
        
        
        String url = "jdbc:mysql://localhost:3306/farm in hand";
        String user ="root";
        String pass = "";
        try
            {
                con = DriverManager.getConnection(url,user,pass);
                                
            }
        catch (Exception e)
        {}
        
        
        
        this.setLocationRelativeTo(null);
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        INDAPURTABLE = new javax.swing.JTable();
        SHOWDATA = new javax.swing.JButton();
        BACK = new javax.swing.JButton();
        PRINT = new javax.swing.JButton();
        CLOSE = new javax.swing.JLabel();
        MINI = new javax.swing.JLabel();
        jLabel1_WALLLL = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 220));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,90));

        INDAPURTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "RATE", "DAY", "MONTH", "YEAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        INDAPURTABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INDAPURTABLEMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(INDAPURTABLE);
        if (INDAPURTABLE.getColumnModel().getColumnCount() > 0) {
            INDAPURTABLE.getColumnModel().getColumn(0).setResizable(false);
            INDAPURTABLE.getColumnModel().getColumn(1).setResizable(false);
            INDAPURTABLE.getColumnModel().getColumn(2).setResizable(false);
            INDAPURTABLE.getColumnModel().getColumn(3).setResizable(false);
            INDAPURTABLE.getColumnModel().getColumn(4).setResizable(false);
            INDAPURTABLE.getColumnModel().getColumn(5).setResizable(false);
        }

        SHOWDATA.setBackground(new java.awt.Color(128, 128, 128));
        SHOWDATA.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        SHOWDATA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/store-sign (1).png"))); // NOI18N
        SHOWDATA.setText(" SHOW DATA");
        SHOWDATA.setBorder(null);
        SHOWDATA.setBorderPainted(false);
        SHOWDATA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SHOWDATA.setOpaque(false);
        SHOWDATA.setSelected(true);
        SHOWDATA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SHOWDATAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SHOWDATAFocusLost(evt);
            }
        });
        SHOWDATA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SHOWDATAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SHOWDATAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SHOWDATAMouseExited(evt);
            }
        });
        SHOWDATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWDATAActionPerformed(evt);
            }
        });

        BACK.setBackground(new java.awt.Color(128, 128, 128));
        BACK.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/arrow-98-24.png"))); // NOI18N
        BACK.setBorder(null);
        BACK.setBorderPainted(false);
        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.setOpaque(false);
        BACK.setSelected(true);
        BACK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BACKFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BACKFocusLost(evt);
            }
        });
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BACKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BACKMouseExited(evt);
            }
        });
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        PRINT.setBackground(new java.awt.Color(128, 128, 128));
        PRINT.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        PRINT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/printer-24.png"))); // NOI18N
        PRINT.setText(" PRINT");
        PRINT.setBorder(null);
        PRINT.setBorderPainted(false);
        PRINT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PRINT.setOpaque(false);
        PRINT.setSelected(true);
        PRINT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PRINTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PRINTFocusLost(evt);
            }
        });
        PRINT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRINTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PRINTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PRINTMouseExited(evt);
            }
        });
        PRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SHOWDATA, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRINT, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SHOWDATA, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(PRINT, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addComponent(BACK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 540, 250));

        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/redclose.png"))); // NOI18N
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLOSEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLOSEMouseExited(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 27, 27));

        MINI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/MINIM.png"))); // NOI18N
        MINI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MINI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MINIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MINIMouseExited(evt);
            }
        });
        getContentPane().add(MINI, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 27, 27));

        jLabel1_WALLLL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/APMCM.jpg"))); // NOI18N
        getContentPane().add(jLabel1_WALLLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        setSize(new java.awt.Dimension(600, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void INDAPURTABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INDAPURTABLEMouseClicked
           
         
    }//GEN-LAST:event_INDAPURTABLEMouseClicked

    private void SHOWDATAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SHOWDATAFocusGained
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GRAY);
        SHOWDATA.setBorder(panelm);
        //jButton_FARM.setBackground(Color.GRAY);
    }//GEN-LAST:event_SHOWDATAFocusGained

    private void SHOWDATAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SHOWDATAFocusLost
        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        SHOWDATA.setBorder(panelm);
        //jButton_FARM.setBackground(Color.GREEN);
    }//GEN-LAST:event_SHOWDATAFocusLost

    private void SHOWDATAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SHOWDATAMouseClicked
        
            //Class.forName("com.mysql.jdbc.Driver");
            //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/indapur","root","");
          /*  String sql = "SELECT * FROM `indapurapmc`"; 
            try 
            {
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                DefaultTableModel TBmodel = (DefaultTableModel)INDAPURTABLE.getModel();
                TBmodel.setNumRows(0);
                        while (rs.next())
                        {
                            TBmodel.addRow(new String[]{rs.getString(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
                            
                            
                        }
                
                
                
            }catch(Exception e){}
        */
        
        
    }//GEN-LAST:event_SHOWDATAMouseClicked

    private void SHOWDATAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SHOWDATAMouseEntered
        Border panelm = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        SHOWDATA.setBorder(panelm);
        SHOWDATA.setBackground(Color.GREEN);
    }//GEN-LAST:event_SHOWDATAMouseEntered

    private void SHOWDATAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SHOWDATAMouseExited

        Border panelm = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.gray);
        SHOWDATA.setBorder(panelm);
        SHOWDATA.setBackground(Color.gray);
    }//GEN-LAST:event_SHOWDATAMouseExited

    private void CLOSEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseEntered
       Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.red);
        CLOSE.setBorder(panelCE);
    }//GEN-LAST:event_CLOSEMouseEntered

    private void CLOSEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseExited
        Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        CLOSE.setBorder(panelCE);
    }//GEN-LAST:event_CLOSEMouseExited

    private void MINIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINIMouseEntered
      Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.gray);
        MINI.setBorder(panelCE);
    }//GEN-LAST:event_MINIMouseEntered

    private void MINIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINIMouseExited
       Border panelCE = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        MINI.setBorder(panelCE);
    }//GEN-LAST:event_MINIMouseExited

    private void CLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseClicked
        this.dispose();
    }//GEN-LAST:event_CLOSEMouseClicked

    private void BACKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BACKFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKFocusGained

    private void BACKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BACKFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKFocusLost

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        APMCS AP = new APMCS();
        AP.show();
        this.dispose();
    }//GEN-LAST:event_BACKMouseClicked

    private void BACKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseEntered
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        BACK.setBorder(panelA);
        BACK.setBackground(Color.GREEN);
    }//GEN-LAST:event_BACKMouseEntered

    private void BACKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseExited
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY);
        BACK.setBorder(panelA);
        BACK.setBackground(Color.GRAY);
    }//GEN-LAST:event_BACKMouseExited

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BACKActionPerformed

    private void SHOWDATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWDATAActionPerformed
        String sql = "SELECT * FROM `indapur_update`"; 
            try 
            {
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                DefaultTableModel TBmodel = (DefaultTableModel)INDAPURTABLE.getModel();
                TBmodel.setNumRows(0);
                        while (rs.next())
                        {
                            TBmodel.addRow(new String[]{rs.getString(1),rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
                            
                            
                        }
                
                
                
            }catch(Exception e){}
        
    }//GEN-LAST:event_SHOWDATAActionPerformed

    private void PRINTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PRINTFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTFocusGained

    private void PRINTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PRINTFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTFocusLost

    private void PRINTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTMouseClicked

    private void PRINTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseEntered
        
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        PRINT.setBorder(panelA);
        PRINT.setBackground(Color.GREEN);
        
    }//GEN-LAST:event_PRINTMouseEntered

    private void PRINTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRINTMouseExited
        
        Border panelA = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GRAY);
        PRINT.setBorder(panelA);
        PRINT.setBackground(Color.GRAY);
        
    }//GEN-LAST:event_PRINTMouseExited

    private void PRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINTActionPerformed
        try
        {
            INDAPURTABLE.print();
        }catch(Exception ec){}
    }//GEN-LAST:event_PRINTActionPerformed

    private void MINIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINIMouseClicked
        this.setExtendedState(INDAPUR_APMC.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_MINIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INDAPUR_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INDAPUR_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INDAPUR_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INDAPUR_APMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INDAPUR_APMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JLabel CLOSE;
    public static javax.swing.JTable INDAPURTABLE;
    private javax.swing.JLabel MINI;
    private javax.swing.JButton PRINT;
    private javax.swing.JButton SHOWDATA;
    private javax.swing.JLabel jLabel1_WALLLL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
