import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.util.Timer;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author R K PC
 */
public class LOGINSCR extends javax.swing.JFrame {

    PreparedStatement p;
    ResultSet R;
    
    public LOGINSCR() {
        initComponents();
        
        this.setLocationRelativeTo(null);    // FORM IN CENTER POSITION 
        
        // ICON ACTION'S
        
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMEAGES/redclose.png")));  // GIVE ICON TO CLOSE
        
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMEAGES/MINIM.png")));  // GIVE ICON TO MINIMIZE
        
       // jLabel_userICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMEAGES/userid.png")));  // GIVE ICON TO USER_ID
        
        //jLabel_passICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMEAGES/lock.png")));  // GIVE ICON TO PASSWORD
        
        //jLabel_up.setIcon(new javax.swing.ImageIcon(getClass().getResource("IMEAGES/arrow.png")));  // GIVE ICON TO ARROW (WRONG NOTICE)
        
        // ICON ACTION'S END //
        
        //-----------------------------------------------------------------------------------------------------//
        
        // BORDER ACTION'S START
                
        Border pr = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jPanel_main.setBorder(pr);      // FOR MAIN BODY
        //jPanel_sub.setBorder(pr);      // FOR SUB BODY
        CLOSE.setBorder(pr);      // FOR CLOSE
        MIN.setBorder(pr);    // FOR MINIMIZE
        jPasswordField_passw.setBorder(pr);
        jTextField_ID.setBorder(pr);
        CLOSE.setBorder(pr);
        MIN.setBorder(pr);
        
        
        // BORDER ACTION'S END //
        
        //-----------------------------------------------------------------------------------------------------//
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jTextField_ID = new javax.swing.JTextField();
        jPasswordField_passw = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        CREATEAC = new javax.swing.JLabel();
        GUST = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CLOSE = new javax.swing.JLabel();
        MIN = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MAINWALL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel_main.setBackground(new java.awt.Color(240, 230, 140));
        jPanel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_ID.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jTextField_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_IDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_IDMouseExited(evt);
            }
        });
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        jPanel_main.add(jTextField_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 139, 222, 28));

        jPasswordField_passw.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jPasswordField_passw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordField_passwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordField_passwMouseExited(evt);
            }
        });
        jPanel_main.add(jPasswordField_passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 194, 222, 28));

        jButton_login.setBackground(new java.awt.Color(153, 153, 153));
        jButton_login.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        jButton_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/logins.png"))); // NOI18N
        jButton_login.setText("LogIN");
        jButton_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_loginMouseExited(evt);
            }
        });
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        jPanel_main.add(jButton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 119, 34));

        CREATEAC.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        CREATEAC.setForeground(new java.awt.Color(255, 255, 255));
        CREATEAC.setText("Create an Account First ?");
        CREATEAC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CREATEAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CREATEACMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CREATEACMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CREATEACMouseExited(evt);
            }
        });
        jPanel_main.add(CREATEAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        GUST.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        GUST.setForeground(new java.awt.Color(255, 255, 255));
        GUST.setText("Gust ?");
        GUST.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GUST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GUSTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GUSTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GUSTMouseExited(evt);
            }
        });
        jPanel_main.add(GUST, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/logi.png"))); // NOI18N
        jPanel_main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        CLOSE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/redclose.png"))); // NOI18N
        CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CLOSEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CLOSEMouseExited(evt);
            }
        });
        jPanel_main.add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        MIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/MINIM.png"))); // NOI18N
        MIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MINMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MINMouseExited(evt);
            }
        });
        jPanel_main.add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/userid.png"))); // NOI18N
        jPanel_main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 30, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/lock.png"))); // NOI18N
        jPanel_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 30, 30));

        MAINWALL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMEAGES/OX.jpg"))); // NOI18N
        jPanel_main.add(MAINWALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 454, 319));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
    private void CLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseClicked
        this.dispose();
    }//GEN-LAST:event_CLOSEMouseClicked

    private void CLOSEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseEntered
        Border panelclosES = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.red);
        CLOSE.setBorder(panelclosES);
    }//GEN-LAST:event_CLOSEMouseEntered

    private void CLOSEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseExited
        Border panelclosES = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        CLOSE.setBorder(panelclosES);
    }//GEN-LAST:event_CLOSEMouseExited

    private void MINMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINMouseEntered
        Border panelmini = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE);
        MIN.setBorder(panelmini);
    }//GEN-LAST:event_MINMouseEntered

    private void MINMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINMouseExited
        Border panelmini = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        MIN.setBorder(panelmini);
    }//GEN-LAST:event_MINMouseExited

    private void GUSTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUSTMouseExited
        Border firs = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        GUST.setBorder(firs);
        GUST.setBackground(Color.white);
    }//GEN-LAST:event_GUSTMouseExited

    private void GUSTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUSTMouseEntered
        Border firs = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.green);
        GUST.setBorder(firs);
        GUST.setBackground(Color.white);
    }//GEN-LAST:event_GUSTMouseEntered

    private void GUSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GUSTMouseClicked
        GOUST_PAGE GP = new GOUST_PAGE();
        GP.show();
        dispose();
    }//GEN-LAST:event_GUSTMouseClicked

    private void CREATEACMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEACMouseExited
        Border firs = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.black);
        CREATEAC.setBorder(firs);
        CREATEAC.setBackground(Color.white);
    }//GEN-LAST:event_CREATEACMouseExited

    private void CREATEACMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEACMouseEntered
        //[240,230,140]
        Border firs = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.green);
        CREATEAC.setBorder(firs);
        CREATEAC.setBackground(Color.white);
    }//GEN-LAST:event_CREATEACMouseEntered

    private void CREATEACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CREATEACMouseClicked
        RAGISTER REG = new RAGISTER();
        REG.show();
        this.dispose();
    }//GEN-LAST:event_CREATEACMouseClicked

    public boolean verify()
    { 
        if(jTextField_ID.getText().equals("") || jPasswordField_passw.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"ID & PASSWORD IS NOT FILLED");
            return false;
        }
        if(jTextField_ID.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null,"ENTER YOUR USER ID");
        return false;
        }   
        else if (jPasswordField_passw.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"ENTER YOUR USER PASSWORD");
            return false;
        }
        else
        {
            return true;
        }
    }
    
    
    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        if (verify())
        {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registration","root","");
            String sql = "SELECT * FROM user_register WHERE USER_NAME=? and PASSWORD=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jTextField_ID.getText());
            pst.setString(2, jPasswordField_passw.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next())
            {
                JOptionPane.showMessageDialog(null,"WELCOME BACK, " + jTextField_ID.getText());
                HOMESCREEN HCR = new HOMESCREEN();
                HCR.show(true);
            }else
            {
                JOptionPane.showMessageDialog(null, "USER IS NOT FOUND IN OUR DATABASE","",JOptionPane.ERROR_MESSAGE);
                jTextField_ID.setText(" ");
                jPasswordField_passw.setText(" ");

            }
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"INVALID DETAIL'S");
        }

    }//GEN-LAST:event_jButton_loginActionPerformed
    }
    private void jButton_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_loginMouseExited
        Border firs = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.GRAY);
        jButton_login.setBorder(firs);
        jButton_login.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButton_loginMouseExited

    private void jButton_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_loginMouseEntered
        Border firs = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.GREEN);
        jButton_login.setBorder(firs);
        jButton_login.setBackground(Color.GREEN);
    }//GEN-LAST:event_jButton_loginMouseEntered

    private void jButton_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_loginMouseClicked
        // 0,0,139
        //Border panellogin = BorderFactory.createMatteBorder(0, 0, 0, 0, Color.red);
        //jButton_login.setBorder(panellogin);
    }//GEN-LAST:event_jButton_loginMouseClicked

    private void jPasswordField_passwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwMouseExited
        /*Border br = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jTextField_ID.setBorder(br);
        jTextField_ID.setBackground(Color.white);*/
    }//GEN-LAST:event_jPasswordField_passwMouseExited

    private void jPasswordField_passwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwMouseEntered
        /*Border br = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        jPasswordField_passw.setBorder(br);
        jPasswordField_passw.setBackground(Color.white);*/
    }//GEN-LAST:event_jPasswordField_passwMouseEntered

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jTextField_IDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_IDMouseExited
        /*Border br = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jPasswordField_passw.setBorder(br);
        jPasswordField_passw.setBackground(Color.white);*/
    }//GEN-LAST:event_jTextField_IDMouseExited

    private void jTextField_IDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_IDMouseEntered
        //Border br = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.blue);
        //jTextField_ID.setBorder(br);
        //jTextField_ID.setBackground(Color.white);
    }//GEN-LAST:event_jTextField_IDMouseEntered

    private void MINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINMouseClicked
        this.setExtendedState(LOGINSCR.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_MINMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINSCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINSCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINSCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINSCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINSCR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOSE;
    private javax.swing.JLabel CREATEAC;
    private javax.swing.JLabel GUST;
    private javax.swing.JLabel MAINWALL;
    private javax.swing.JLabel MIN;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPasswordField jPasswordField_passw;
    private javax.swing.JTextField jTextField_ID;
    // End of variables declaration//GEN-END:variables

    private void executeQuery() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
